packages:
  - ./packages/*
  - ./examples/*
allowBuilds:
  '@prisma/engines': true
  better-sqlite3: true
  dtrace-provider: true
  esbuild: true
  prisma: true
  sqlite3: true
  svelte-preprocess: true
ignoredBuiltDependencies:
  - better-sqlite3
  - prisma
onlyBuiltDependencies:
  - better-sqlite3
