"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var dotenv_1 = require("dotenv");
var client_1 = require("@prisma/client");
var server_1 = require("crossauth/server");
dotenv_1.default.config();
var port = Number(process.env.PORT || 3000);
var prefix = process.env.PREFIX || "";
var prisma = new client_1.PrismaClient();
var userStorage = new server_1.PrismaUserStorage({ prismaClient: prisma });
var sessionStorage = new server_1.PrismaSessionStorage(userStorage, { prismaClient: prisma });
var sessionManager = new server_1.CookieSessionManager(userStorage, sessionStorage);
var server = new server_1.FastifyCookieAuthServer(sessionManager);
server.start(port);
